baseURL = "https://zweroxotnik.github.io"
languageCode = "en-US"
defaultContentLanguage = "ru"

title = "ZwerOxotnik's UC"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/zweroxotnik/zweroxotnik.github.io/edit/main/content/"
  description = "ZwerOxotnik's UC"
  themeVariant = ""
  custom_css = ["css/theme-mine.css"]
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = true
  disableLandingPageButton = true
  disableMermaid = true
  customlazyloadURL = "https://cdn.jsdelivr.net/npm/vanilla-lazyload@17.3.0/dist/lazyload.min.js"
  customMermaidURL = "https://unpkg.com/mermaid@8.9.0/dist/mermaid.min.js"
  customJQuerydURL = "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"
  titleSeparator = "::"
  gaID = "G-730ZQG92D6"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "ZwerOxotnik's UC"
weight = 1
languageName = "English"
landingPageURL = "/en"
landingPageName = "<i class='fas fa-home'></i> Home"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/zweroxotnik/zweroxotnik.github.io"
weight = 10

[Languages.ru]
title = "Объединённый центр ZwerOxotnik'а"
weight = 2
languageName = "Русский"
landingPageURL = "/ru"
landingPageName = "<i class='fas fa-home'></i> Accueil"

[[Languages.ru.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub репозиторий"
identifier = "ds"
url = "https://github.com/zweroxotnik/zweroxotnik.github.io"
weight = 10